apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8080  # 외부에 노출할 포트
      targetPort: 8000  # 컨테이너 내부에서 FastAPI가 사용하는 포트
  type: LoadBalancer  # 로드 밸런서 설정 (K3s에서는 기본적으로 Traefik을 사용)

