apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # values.yaml에서 참조
      targetPort: {{ .Values.service.targetPort }}  # values.yaml에서 참조
  type: {{ .Values.service.type }}  # values.yaml에서 참조
